apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
  name: cluster
spec:
  identityProviders:
  - mappingMethod: ${MAPPING}
    name: ${IDENTITY_PROVIDER}
    openID:
      claims:
        preferredUsername:
        - preferred_username
      clientID: crtoolchain
      clientSecret:
        name: rhd-idp-secret
      issuer: ${ISSUER}
    type: OpenID
