apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "${MACHINE_AUTOSCALER_NAME}"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 3
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: ${MACHINE_SET}
