apiVersion: v1
data:
  mailgun.domain: ${MAILGUN_DOMAIN}
  mailgun.api.key: ${MAILGUN_API_KEY}
  mailgun.sender.email: ${MAILGUN_SENDER_EMAIL}
kind: Secret
metadata:
  name: host-operator-secret
  namespace: ${NAMESPACE}
type: Opaque