apiVersion: v1
kind: ConfigMap
metadata:
  name: member-operator-config
  namespace: ${NAMESPACE}
type: Opaque
data:
  che.namespace: "codeready-workspaces-operator"
  che.route.name: "codeready"
  che.user_deletion_enabled: "true"
  identity.provider: ${IDENTITY_PROVIDER}
