kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: host-crt-stage-com
  namespace: toolchain-host-operator
spec:
  host: www.apps.host.crt-stage.com
  to:
    kind: Service
    name: registration-service
    weight: 100
  port:
    targetPort: '8080'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
