apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterLogging.v1.logging.openshift.io
  generateName: openshift-logging-
  generation: 1
spec:
  targetNamespaces:
  - openshift-logging