{
 "title": "Dev Sandbox",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Operator CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "namespace:container_cpu_usage_seconds_total:sum_rate{namespace=~\".*-host-operator\"}",
     "legendFormat": "host-operator"
    },
    {
     "expr": "namespace:container_cpu_usage_seconds_total:sum_rate{namespace=~\".*-member-operator\"}",
     "legendFormat": "member-operator"
    }
   ]
  },
  {
   "title": "Active users (total)",
   "type": "graph",
   "description": "Tracking the total number of MasterUserRecord resources",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sandbox_master_user_record_current)",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Operator Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(namespace:container_memory_usage_bytes:sum{namespace=~\".*-host-operator\"}[1m])\n",
     "legendFormat": "host-operator"
    },
    {
     "expr": "avg_over_time(namespace:container_memory_usage_bytes:sum{namespace=~\".*-member-operator\"}[1m])",
     "legendFormat": "member-operator"
    }
   ]
  },
  {
   "title": "Activity (rate on 5m)",
   "type": "graph",
   "description": "Tracking evolution of approved, deactivated and banned users",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(sandbox_user_signups_approved_total[5m]))*60",
     "legendFormat": "approved/min"
    },
    {
     "expr": "sum by (service) (rate(sandbox_user_signups_banned_total[5m]))*60",
     "legendFormat": "banned/min"
    },
    {
     "expr": "sum by (service) (rate(sandbox_user_signups_deactivated_total[5m]))*60",
     "legendFormat": "deactivated/min"
    }
   ]
  }
 ]
}