apiVersion: v1
kind: Template
metadata:
  name: grafana-serviceaccount-template
  annotations:
    tags: "grafana,monitoring"
labels:
  # will be applied on all objects defined below
  app: grafana 
parameters:
- name: NAMESPACE
  description: The namespace in which to create these Grafana resources
  required: true
- name: NAME
  description: The name of the ServiceAccount to create
  required: true

objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: ${NAMESPACE}
    name: ${NAME}
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'

