apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: toolchain-grafana
  name: grafana
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'

