apiVersion: v1
kind: Template
metadata:
  name: grafana-serviceaccount-template
  annotations:
    tags: "grafana,monitoring"
labels:
  # will be applied on all objects defined below
  app: grafana 
parameters:
- name: NAME
  description: The name of the namespace to create
  required: true

objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${NAME}